# -*- coding: utf-8 -*-
"""MINMAX*.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0QYHrfC9EsCXkbqcI6--1qPrdRS9tlK
"""

def find_min_max(arr):
    if len(arr) == 0:
        return None, None  # Handle empty list case

    min_val = arr[0]
    max_val = arr[0]

    for num in arr[1:]:
        if num < min_val:
            min_val = num
        if num > max_val:
            max_val = num

    return min_val, max_val


# Example usage:
arr = [3, 1, 7, 2, 9, 5]
min_value, max_value = find_min_max(arr)
print("Minimum value:", min_value)
print("Maximum value:", max_value)